export const GET_CARDS_REQUEST = 'GET_CARDS_REQUEST'
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS'
export const GET_CARDS_FAIL = 'GET_CARDS_FAIL'

export const GET_TOP_ORDER_REQUEST = 'GET_TOP_ORDER_REQUEST'
export const GET_TOP_ORDER_SUCCESS = 'GET_TOP_ORDER_SUCCESS'
export const GET_TOP_ORDER_FAIL = 'GET_TOP_ORDER_FAIL'

export const GET_LAST_ORDER_REQUEST = 'GET_LAST_ORDER_REQUEST'
export const GET_LAST_ORDER_SUCCESS = 'GET_LAST_ORDER_SUCCESS'
export const GET_LAST_ORDER_FAIL = 'GET_LAST_ORDER_FAIL'

export const GET_PRODUCT_TRENDING_REQUEST = "GET_PRODUCT_TRENDING_REQUEST"
export const GET_PRODUCT_TRENDING_SUCCESS = "GET_PRODUCT_TRENDING_SUCCESS"
export const GET_PRODUCT_TRENDING_FAIL = "GET_PRODUCT_TRENDING_FAIL"


export const GET_CATE_TRENDING_REQUEST = "GET_CATE_TRENDING_REQUEST"
export const GET_CATE_TRENDING_SUCCESS = "GET_CATE_TRENDING_SUCCESS"
export const GET_CATE_TRENDING_FAIL = "GET_CATE_TRENDING_FAIL"
